<a href="https://colab.research.google.com/github/Ishan-max/Ishan-max/blob/main/Data_Cleaning_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('/content/healthcare_data_cleaning_dataset.csv')

df.head()

,Patient_ID,Age,Gender,City,Diagnosis,Hospital_Visits,Treatment_Cost,Insurance_Coverage,Admission_Date
0,17270,35.0,Male,Bangalore,Hypertension,13,41010.0,1,2023-11-30
1,10860,21.0,Female,Hyderabad,Flu,11,12194.0,1,2023-02-23
2,15390,77.0,Female,Bangalore,Asthma,2,45086.0,0,2023-03-14
3,15191,79.0,Female,Mumbai,Asthma,13,40842.0,0,2023-08-01
4,15734,60.0,Female,Delhi,Asthma,1,9873.0,1,2023-06-20

Q1. Missing Data Identification

Scenario:
 The hospital suspects incomplete patient records.

Task:

Identify missing values in each column

Calculate percentage of missing data

In [2]:
missing_values = df.isnull().sum()
missing_values_percentage = (missing_values / len(df)) * 100

print("Missing Values:")
print(missing_values)
print("\nPercentage of Missing Data:")
print(missing_values_percentage)

Missing Values:
Patient_ID              0
Age                   600
Gender                  0
City                    0
Diagnosis               0
Hospital_Visits         0
Treatment_Cost        593
Insurance_Coverage      0
Admission_Date          0
dtype: int64

Percentage of Missing Data:
Patient_ID             0.000000
Age                   11.764706
Gender                 0.000000
City                   0.000000
Diagnosis              0.000000
Hospital_Visits        0.000000
Treatment_Cost        11.627451
Insurance_Coverage     0.000000
Admission_Date         0.000000
dtype: float64

Q2. Handling Missing Age

Scenario:
 Age is critical for medical analysis, but some values are missing.

Task:

Replace missing Age values with an appropriate method

Justify your choice (mean/median)

In [3]:
''' Missing values in the Age column were replaced using the median because age data may contain outliers.
 The median is more robust than the mean and provides a better representation of the central tendency of the data
  without being heavily influenced by extreme values.'''



df['Age'] = df['Age'].fillna(df['Age'].median())

df['Age']

0       35.0
1       21.0
2       77.0
3       79.0
4       60.0
        ...
5095    50.0
5096    50.0
5097    50.0
5098    50.0
5099    50.0
Name: Age, Length: 5100, dtype: float64

Q3. Handling Missing Treatment Cost

Scenario:
 Treatment cost is highly skewed due to expensive treatments.

Task:

Handle missing Treatment_Cost values

Choose the correct imputation method and explain why

In [4]:
''' Handle missing Treatment_Cost values
Choose the correct imputation method and explain why '''

df['Treatment_Cost'] = df['Treatment_Cost'].fillna(df['Treatment_Cost'].median())

df['Treatment_Cost']

0       41010.0
1       12194.0
2       45086.0
3       40842.0
4        9873.0
         ...
5095    24797.0
5096    24797.0
5097    24797.0
5098    24797.0
5099    24797.0
Name: Treatment_Cost, Length: 5100, dtype: float64

Q4. Duplicate Patient Records

Scenario:
 Some patient records were entered multiple times.

Task:

Identify duplicate rows

Remove duplicates

Compare dataset size before and after

In [5]:
# Dataset size before
print("Dataset Size Before:", df.shape)

# Identify duplicates
duplicates = df[df.duplicated()]
print("\nDuplicate Rows:")
print(duplicates)

# Remove duplicates
df = df.drop_duplicates()

# Dataset size after
print("\nDataset Size After:", df.shape)

Dataset Size Before: (5100, 9)

Duplicate Rows:
      Patient_ID   Age  Gender       City     Diagnosis  Hospital_Visits  \
5000       15126  50.0    Male  Hyderabad        Asthma                1
5001       15108  50.0    Male  Hyderabad        Asthma                3
5002       10441  50.0    Male    Chennai           Flu                3
5003       15975  50.0  Female  Hyderabad           Flu               10
5004       18427  50.0  Female      Delhi      COVID-19               13
...          ...   ...     ...        ...           ...              ...
5094       11571  50.0  Female    Chennai      COVID-19                4
5096       17597  50.0  Female    Chennai        Asthma                2
5097       19171  50.0  Female     Mumbai           Flu                1
5098       13854  50.0  Female  Bangalore           Flu               17
5099       14859  50.0    Male      Delhi  Hypertension               19

      Treatment_Cost  Insurance_Coverage Admission_Date
5000         24797.0                   1     2023-01-19
5001         24797.0                   0     2023-01-27
5002         24797.0                   0     2023-07-08
5003         24797.0                   0     2023-06-01
5004         24797.0                   1     2023-03-04
...              ...                 ...            ...
5094         24797.0                   0     2023-01-28
5096         24797.0                   0     2023-06-26
5097         24797.0                   1     2023-12-31
5098         24797.0                   0     2023-01-18
5099         24797.0                   0     2023-08-28

[99 rows x 9 columns]

Dataset Size After: (5001, 9)

Q5. Invalid Age Values (Data Quality Check)

Scenario:
 Some patients have unrealistic age values (e.g., >100 or <0).

Task:

Detect such records

Decide whether to remove or correct them

In [11]:
# find invalid age

# Find records with invalid ages


median_age = df[(df['Age'] >= 0) & (df['Age'] <= 100)]['Age'].median()

df.loc[(df['Age'] < 0) | (df['Age'] > 100), 'Age'] = median_age

print(df)

      Patient_ID   Age  Gender       City     Diagnosis  Hospital_Visits  \
0          17270  35.0    Male  Bangalore  Hypertension               13
1          10860  21.0  Female  Hyderabad           Flu               11
2          15390  77.0  Female  Bangalore        Asthma                2
3          15191  79.0  Female     Mumbai        Asthma               13
4          15734  60.0  Female      Delhi        Asthma                1
...          ...   ...     ...        ...           ...              ...
4996       16135  50.0  Female      Delhi  Hypertension               13
4997       15573  35.0  Female      Delhi      COVID-19               19
4998       14131  60.0  Female    Chennai  Hypertension                4
4999       19900  16.0  Female    Chennai           Flu               16
5095       11764  50.0  Female     Mumbai      COVID-19               15

      Treatment_Cost  Insurance_Coverage Admission_Date
0            41010.0                   1     2023-11-30
1            12194.0                   1     2023-02-23
2            45086.0                   0     2023-03-14
3            40842.0                   0     2023-08-01
4             9873.0                   1     2023-06-20
...              ...                 ...            ...
4996         24797.0                   1     2023-11-02
4997          2585.0                   1     2023-12-02
4998         31337.0                   0     2023-04-07
4999         39801.0                   0     2023-08-04
5095         24797.0                   0     2023-09-22

[5001 rows x 9 columns]

Q6. Outlier Detection (Treatment Cost)

Scenario:
 Extreme treatment costs are affecting analysis.

Task:

Detect outliers using IQR method

Display number of outliers

In [ ]:
# Calculate Q1 and Q3

Q1 = df['Treatment_Cost'].quantile(0.25)
Q3 = df['Treatment_Cost'].quantile(0.75)

# Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1

# Define the lower and upper bounds for outliers

lower_band = Q1 - 1.5 * IQR
upper_band = Q3 + 1.5 * IQR

# Identify outliers
outliers = df[
    (df['Treatment_Cost'] < lower_band) | (df['Treatment_Cost'] > upper_band)
]

print("Outlier Records:")
print(outliers)

# Display number of outliers
print("Number of Outliers:", len(outliers))

Q7. Outlier Treatment

Scenario:
The business team wants to retain all records.

Task:

Apply capping (Winsorization) on Treatment_Cost

Use 5th and 95th percentile

In [ ]:
# calculate 5th and 95th percentiles

lower_limit = df['Treatment_Cost'].quantile(0.05)
upper_limit = df['Treatment_Cost'].quantile(0.95)

# Apply capping on Treatment_Cost
df['Treatment_Cost'] = df['Treatment_Cost'].clip(
    lower=lower_limit,
    upper=upper_limit
)

print(df)

print(lower_limit)
print(upper_limit)

print(df['Treatment_Cost'].describe())

Q8. Transformation

Scenario:
 Treatment cost is highly skewed.

Task:

Apply log transformation

Create a new column

Compare before vs after distribution

In [ ]:
import numpy as np

# create log-transformed column

df['Log_Treatment_Cost'] = np.log1p(df['Treatment_Cost'])

print(df[['Treatment_Cost', 'Log_Treatment_Cost']].head())



print("Before Transformation")
print(df['Treatment_Cost'].describe())

print("After Transformation")
print(df['Log_Treatment_Cost'].describe())

print("Skewness Before:", df['Treatment_Cost'].skew())
print("Skewness After:", df['Log_Treatment_Cost'].skew())

import matplotlib.pyplot as plt

# Original Distribution

plt.hist(df['Treatment_Cost'], bins = 20 )
plt.title('Treatmeant_Cost_Distribution')
plt.show()

# Log-Transferred distribution

plt.hist(df['Log_Treatment_Cost'], bins = 20)
plt.title('Log_Treatmeant_Cost_Distribution')
plt.show()

Q9. Time-Based Missing Handling

Scenario : Admission dates should follow a logical sequence.


Task : Sort data by Admission_Date Apply forward fill or backward fill where appropriate Justify your choice

In [ ]:
# sort data by admission date

df = df.sort_values(by = 'Admission_Date')

df.fillna(method = 'ffill', inplace = True)

print(df)

df.fillna(method = 'bfill', inplace = True)

print(df)