<a href="https://colab.research.google.com/github/Ishan-max/Ishan-max/blob/main/Python%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/retail_dataset.csv')
df

df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [ ]:
print(df.isnull().sum())

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [ ]:
# replace null value with mean of the columns

df.fillna({
    'Quantity' : df['Quantity'].mean(),
    'Price' : df['Price'].mean()
}, inplace=True )

print(df)

   Transaction ID Customer ID Product Category  Quantity   Price        Date  \
0            T001        C015            Books       7.0   167.0  02-02-2023
1            T002        C004             Toys       4.0   374.0  17-02-2023
2            T003        C033        Furniture       8.0  1059.0  17-05-2024
3            T004        C047        Groceries       5.0   304.0  11-02-2024
4            T005        C022            Books       7.0   282.0  27-07-2024
..            ...         ...              ...       ...     ...         ...
95           T096        C036        Furniture      10.0  2901.0  08-08-2023
96           T097        C021         Clothing       9.0  1077.0  19-07-2024
97           T098        C015         Clothing       7.0   643.0  13-08-2023
98           T099        C005        Groceries       9.0   429.0  20-01-2024
99           T100        C010        Furniture       8.0  1183.0  07-02-2024

   Region
0   North
1   South
2   South
3   South
4    West
..    ...
95  North
96  North
97  North
98  South
99  North

[100 rows x 7 columns]

In [ ]:
df.dropna(subset=['Product Category', 'Region'], inplace=True)

print(df)

   Transaction ID Customer ID Product Category  Quantity   Price        Date  \
0            T001        C015            Books       7.0   167.0  02-02-2023
1            T002        C004             Toys       4.0   374.0  17-02-2023
2            T003        C033        Furniture       8.0  1059.0  17-05-2024
3            T004        C047        Groceries       5.0   304.0  11-02-2024
4            T005        C022            Books       7.0   282.0  27-07-2024
..            ...         ...              ...       ...     ...         ...
95           T096        C036        Furniture      10.0  2901.0  08-08-2023
96           T097        C021         Clothing       9.0  1077.0  19-07-2024
97           T098        C015         Clothing       7.0   643.0  13-08-2023
98           T099        C005        Groceries       9.0   429.0  20-01-2024
99           T100        C010        Furniture       8.0  1183.0  07-02-2024

   Region
0   North
1   South
2   South
3   South
4    West
..    ...
95  North
96  North
97  North
98  South
99  North

[95 rows x 7 columns]

In [ ]:
print(df.isnull().sum())

Transaction ID      0
Customer ID         0
Product Category    0
Quantity            0
Price               0
Date                0
Region              0
dtype: int64

In [ ]:
import numpy as np
import pandas as pd


df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0
...,...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North,29010.0
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North,9693.0
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North,4501.0
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South,3861.0
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North,9464.0

In [ ]:
total_revenue = np.sum(df['Revenue'])
total_revenue

print('Total Revenue', total_revenue)

Total Revenue 465529.66058002145

In [ ]:
category_revenue = df.groupby('Product Category')['Revenue'].sum()
print(category_revenue)

Product Category
Beauty          27647.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            53947.879699
Name: Revenue, dtype: float64

In [ ]:
top_3 = category_revenue.nlargest(3)
print(top_3)



bottom_3 = category_revenue.nsmallest(3)
print(bottom_3)

Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64
Product Category
Groceries    11978.000000
Beauty       27647.000000
Books        29597.938776
Name: Revenue, dtype: float64

In [ ]:
region_revenue = df.groupby('Region', as_index=False)['Revenue'].sum()

Highest_revenue = region_revenue.sort_values('Revenue', ascending=False).head(1)
Lowest_revenue = region_revenue.sort_values('Revenue').head(1)

print(Highest_revenue)
print(Lowest_revenue)

  Region        Revenue
1  North  153244.353383
  Region       Revenue
3   West  81197.526316

In [ ]:
import pandas as pd
import numpy as np

# Convert date column to datetime format
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

# Extract month from date column

df['Month'] = df['Date'].dt.month

monthly_revenue = df.groupby('Month', as_index=False)['Revenue'].sum()

print(round(monthly_revenue,2))

# Calculate mean, median and standard deviation of Revenue

mean_revenue = np.mean(df['Revenue'])
median_revenue = np.median(df['Revenue'])
std_revenue = np.std(df['Revenue'])

print("\n Revenue Statisctics:")
print("Mean:", round(mean_revenue,2))
print("Median:",round( median_revenue,2))
print("Standard Deviation:", round(std_revenue,2 ))

    Month   Revenue
0       1  43994.00
1       2  33028.00
2       3  10557.00
3       4  57298.53
4       5  27915.00
5       6  28190.00
6       7  47851.29
7       8  76958.00
8       9  30719.11
9      10  38017.00
10     11  27662.74
11     12  43339.00

 Revenue Statisctics:
Mean: 4900.31
Median: 3282.11
Standard Deviation: 4721.17